In [1]:
import pandas as pd
import numpy as np

from synthesize import SyntheticEmpiricalDataset

In [2]:
metadata = pd.read_csv("../../allen_mouse_brain_atlas_dataset/metadata.csv")
metadata

sample_name  \
0        ACTGAGTAGGTGACCA-L8TX_180221_01_C11   
1        TCAACGACAGACAGGT-L8TX_180221_01_B11   
2        CTCGTACTCACGACTA-L8TX_180221_01_C11   
3        CACCAGGCAGGTCTCG-L8TX_180221_01_C11   
4        GACTGCGCAAAGGTGC-L8TX_180221_01_C11   
...                                      ...   
1093031  TTTGTCATCTTTACGT-L8TX_180221_01_E10   
1093032  TTTGTCATCTTTACGT-L8TX_180221_01_A10   
1093033  TTTGTCATCTTTAGGG-L8TX_181012_01_E05   
1093034  TTTGTCATCTTTAGTC-L8TX_180115_01_E09   
1093035  TTTGTCATCTTTAGTC-L8TX_180712_01_E05   

                            exp_component_name platform_label cluster_color  \
0         ACTGAGTAGGTGACCA-2L8TX_180221_01_C11            10x       #5E5765   
1         TCAACGACAGACAGGT-1L8TX_180221_01_B11            10x       #5E5765   
2         CTCGTACTCACGACTA-2L8TX_180221_01_C11            10x       #5E5765   
3         CACCAGGCAGGTCTCG-2L8TX_180221_01_C11            10x       #5E5765   
4         GACTGCGCAAAGGTGC-2L8TX_180221_01_C11            10x       #5E5765   
...                                        ...            ...           ...   
1093031   TTTGTCATCTTTACGT-2L8TX_180221_01_E10            10x       #04EC5E   
1093032   TTTGTCATCTTTACGT-4L8TX_180221_01_A10            10x       #07C6D9   
1093033  TTTGTCATCTTTAGGG-11L8TX_181012_01_E05            10x       #996068   
1093034  TTTGTCATCTTTAGTC-22L8TX_180115_01_E09            10x       #00FFFF   
1093035   TTTGTCATCTTTAGTC-6L8TX_180712_01_E05            10x       #55C5B5   

         cluster_order    cluster_label class_color  class_order  \
0                355.0          355_V3d     #00ADEE          2.0   
1                355.0          355_V3d     #00ADEE          2.0   
2                355.0          355_V3d     #00ADEE          2.0   
3                355.0          355_V3d     #00ADEE          2.0   
4                355.0          355_V3d     #00ADEE          2.0   
...                ...              ...         ...          ...   
1093031          179.0  179_L2/3 IT CTX     #00ADEE          2.0   
1093032          196.0  196_L4/5 IT CTX     #00ADEE          2.0   
1093033            9.0          9_Lamp5     #F05A28          1.0   
1093034          188.0  188_L4/5 IT CTX     #00ADEE          2.0   
1093035          205.0    205_L5 IT CTX     #00ADEE          2.0   

           class_label subclass_color  ...  injection_method_label  \
0        Glutamatergic        #5E5765  ...                     NaN   
1        Glutamatergic        #5E5765  ...                     NaN   
2        Glutamatergic        #5E5765  ...                     NaN   
3        Glutamatergic        #5E5765  ...                     NaN   
4        Glutamatergic        #5E5765  ...                     NaN   
...                ...            ...  ...                     ...   
1093031  Glutamatergic        #0BE652  ...                     NaN   
1093032  Glutamatergic        #00E5E5  ...                     NaN   
1093033      GABAergic        #DA808C  ...                     NaN   
1093034  Glutamatergic        #00E5E5  ...                     NaN   
1093035  Glutamatergic        #50B2AD  ...                     NaN   

        injection_roi_color injection_roi_id  injection_roi_label  \
0                   #FF7373                1                  NaN   
1                   #FF7373                1                  NaN   
2                   #FF7373                1                  NaN   
3                   #FF7373                1                  NaN   
4                   #FF7373                1                  NaN   
...                     ...              ...                  ...   
1093031             #FF7373                1                  NaN   
1093032             #FF7373                1                  NaN   
1093033             #FF7373                1                  NaN   
1093034             #FF7373                1                  NaN   
1093035             #FF7373                1                  NaN   

        injection_ty

In [3]:
means = pd.read_csv("../../allen_mouse_brain_atlas_dataset/trimmed_means.csv")
medians = pd.read_csv("../../allen_mouse_brain_atlas_dataset/medians.csv")

In [4]:
means

feature  108_Pvalb  229_L6 IT CTX     67_Sst  6_Lamp5 Lhx6  \
0                Xkr4   9.775850       7.849091  10.150249         9.220   
1              Gm1992   0.000000       0.000000   0.000000         0.000   
2             Gm37381   0.000000       0.000000   0.000000         0.000   
3                 Rp1   0.000000       0.000000   0.000000         0.000   
4               Sox17   0.000000       0.000000   0.000000         0.000   
...               ...        ...            ...        ...           ...   
31048      AC168977.1   0.000000       0.000000   0.000000         0.000   
31049      AC149090.1   4.219954       7.173148   4.542934         7.972   
31050  CAAA01118383.1   0.000000       0.000000   0.000000         0.000   
31051        Vmn2r122   0.000000       0.000000   0.000000         0.000   
31052  CAAA01147332.1   0.000000       0.000000   0.000000         0.000   

       111_Pvalb   293_CA3  323_L6 CT CTX    17_Pax6  261_L6 Car3  ...  \
0      10.064405  8.947619       9.311210  10.252500     7.900000  ...   
1       0.135898  0.078065       0.000000   0.313115     0.000000  ...   
2       0.000000  0.000000       0.000000   0.000000     0.000000  ...   
3       0.000000  0.000000       0.000000   0.000000     0.000000  ...   
4       0.000000  0.000000       0.000000   0.000000     0.000000  ...   
...          ...       ...            ...        ...          ...  ...   
31048   0.000000  0.000000       0.000000   0.000000     0.000000  ...   
31049   6.997127  7.141220       7.107702   7.851750     3.891463  ...   
31050   0.000000  0.000000       0.000000   0.000000     0.000000  ...   
31051   0.000000  0.000000       0.000000   0.000000     0.000000  ...   
31052   0.000000  0.000000       0.000000   0.000000     0.000000  ...   

       190_L4/5 IT CTX   298_CA3  314_NP SUB  340_L6b CTX  139_L2 IT ENTl  \
0              8.57850  9.172284    7.930078     9.624958        8.869418   
1              0.00000  0.334232    0.000000     0.126433        0.000000   
2              0.00000  0.000000    0.000000     0.000000        0.000000   
3              0.00000  0.000000    0.000000     0.000000        0.000000   
4              0.00000  0.000000    0.000000     0.000000        0.000000   
...                ...       ...         ...          ...             ...   
31048          0.00000  0.000000    0.000000     0.000000        0.000000   
31049          4.22592  7.496149    7.790364     6.663613        6.913958   
31050          0.00000  0.000000    0.000000     0.000000        0.000000   
31051          0.00000  0.000000    0.000000     0.000000        0.000000   
31052          0.00000  0.000000    0.000000     0.000000        0.000000   

       210_L5 IT TPE-ENT  370_Endo  257_L5 PPP  273_CA1-ProS  138_L2 IT ENTl  
0               8.784914  0.000000    8.209695      7.273118        8.823500  
1               0.000000  0.000000    0.000000      0.000000        0.000000  
2               0.000000  0.000000    0.000000      0.000000        0.000000  
3               0.000000  0.000000    0.000000      0.000000        0.000000  
4               0.000000  2.990461    0.000000      0.000000        0.000000  
...                  ...       ...         ...           ...             ...  
31048           0.000000  0.000000    0.000000      0.000000        0.000000  
31049           7.464549  0.111044    7.251495      7.313517        4.114286  
31050           0.000000  0.000000    0.000000      0.000000        0.000000  
31051           0.000000  0.000000    0.000000      0.000000        0.000000  
31052           0.000000  0.000000    0.000000      0.000000        0.000000  

[31053 rows x 379 columns]

In [5]:
medians

feature  108_Pvalb  229_L6 IT CTX  67_Sst  6_Lamp5 Lhx6  \
0                Xkr4       9.82          7.840   10.16          9.17   
1              Gm1992       0.00          0.000    0.00          0.00   
2             Gm37381       0.00          0.000    0.00          0.00   
3                 Rp1       0.00          0.000    0.00          0.00   
4               Sox17       0.00          0.000    0.00          0.00   
...               ...        ...            ...     ...           ...   
31048      AC168977.1       0.00          0.000    0.00          0.00   
31049      AC149090.1       7.11          7.195    7.40          8.00   
31050  CAAA01118383.1       0.00          0.000    0.00          0.00   
31051        Vmn2r122       0.00          0.000    0.00          0.00   
31052  CAAA01147332.1       0.00          0.000    0.00          0.00   

       111_Pvalb  293_CA3  323_L6 CT CTX  17_Pax6  261_L6 Car3  ...  \
0          10.08     8.96           9.33   10.300         7.91  ...   
1           0.00     0.00           0.00    0.000         0.00  ...   
2           0.00     0.00           0.00    0.000         0.00  ...   
3           0.00     0.00           0.00    0.000         0.00  ...   
4           0.00     0.00           0.00    0.000         0.00  ...   
...          ...      ...            ...      ...          ...  ...   
31048       0.00     0.00           0.00    0.000         0.00  ...   
31049       7.08     7.21           7.16    7.935         6.26  ...   
31050       0.00     0.00           0.00    0.000         0.00  ...   
31051       0.00     0.00           0.00    0.000         0.00  ...   
31052       0.00     0.00           0.00    0.000         0.00  ...   

       190_L4/5 IT CTX  298_CA3  314_NP SUB  340_L6b CTX  139_L2 IT ENTl  \
0                 8.59     9.17        7.96         9.64            8.89   
1                 0.00     0.00        0.00         0.00            0.00   
2                 0.00     0.00        0.00         0.00            0.00   
3                 0.00     0.00        0.00         0.00            0.00   
4                 0.00     0.00        0.00         0.00            0.00   
...                ...      ...         ...          ...             ...   
31048             0.00     0.00        0.00         0.00            0.00   
31049             6.80     7.46        7.81         6.69            6.97   
31050             0.00     0.00        0.00         0.00            0.00   
31051             0.00     0.00        0.00         0.00            0.00   
31052             0.00     0.00        0.00         0.00            0.00   

       210_L5 IT TPE-ENT  370_Endo  257_L5 PPP  273_CA1-ProS  138_L2 IT ENTl  
0                   8.80     0.000        8.25          7.31            8.89  
1                   0.00     0.000        0.00          0.00            0.00  
2                   0.00     0.000        0.00          0.00            0.00  
3                   0.00     0.000        0.00          0.00            0.00  
4                   0.00     7.635        0.00          0.00            0.00  
...                  ...       ...         ...           ...             ...  
31048               0.00     0.000        0.00          0.00            0.00  
31049               7.57     0.000        7.32          7.33            6.64  
31050               0.00     0.000        0.00          0.00            0.00  
31051               0.00     0.000        0.00          0.00            0.00  
31052               0.00     0.000        0.00          0.00            0.00  

[31053 rows x 379 columns]

In [6]:
layer_specific_cell_types = medians.filter(regex=".*L[1-9][^/b].*").columns
layer_specific_cell_types

Index(['229_L6 IT CTX', '323_L6 CT CTX', '261_L6 Car3', '219_L6 IT CTX',
       '227_L6 IT CTX', '212_L5 IT TPE-ENT', '223_L6 IT CTX', '131_L2 IT RSPv',
       '306_L5 NP CTX', '142_L3 IT ENTm',
       ...
       '154_L2 IT ProS', '143_L3 IT ENTm', '332_L6 CT ENTm', '145_L3 IT ENTl',
       '226_L6 IT CTX', '256_L5 PT RSP-ACA', '139_L2 IT ENTl',
       '210_L5 IT TPE-ENT', '257_L5 PPP', '138_L2 IT ENTl'],
      dtype='object', length=101)

In [7]:
filtered_metadata = metadata[metadata['cell_type_alias_label'].isin(layer_specific_cell_types)]

In [8]:
cell_type_distribution = filtered_metadata['cell_type_alias_label'].value_counts()

In [9]:
layer_specific_cell_types

Index(['229_L6 IT CTX', '323_L6 CT CTX', '261_L6 Car3', '219_L6 IT CTX',
       '227_L6 IT CTX', '212_L5 IT TPE-ENT', '223_L6 IT CTX', '131_L2 IT RSPv',
       '306_L5 NP CTX', '142_L3 IT ENTm',
       ...
       '154_L2 IT ProS', '143_L3 IT ENTm', '332_L6 CT ENTm', '145_L3 IT ENTl',
       '226_L6 IT CTX', '256_L5 PT RSP-ACA', '139_L2 IT ENTl',
       '210_L5 IT TPE-ENT', '257_L5 PPP', '138_L2 IT ENTl'],
      dtype='object', length=101)

In [10]:
layer_distributions = []
for layer in range(2, 7):
    layer_name = f"L{layer}"
    is_matching = layer_specific_cell_types.str.contains(layer_name)
    matching_cell_types = layer_specific_cell_types[is_matching]
    layer_distribution = cell_type_distribution[matching_cell_types]
    print(layer_distribution)
    layer_distributions.append(layer_distribution / layer_distribution.sum())

131_L2 IT RSPv       11859
186_L2 IT RSP-ACA     6771
130_L2 IT RSPv         468
155_L2 IT ProS        1591
148_L2 IT PAR         1124
156_L2 IT ProS          77
147_L2 IT PAR          453
150_L2 IT ENTm         169
151_L2 IT ENTm         253
185_L2 IT RSP-ACA      158
137_L2 IT ENTl         230
153_L2 IT ENTm        1683
149_L2 IT PAR          202
157_L2 IT HATA        1332
152_L2 IT ENTm         412
154_L2 IT ProS         303
139_L2 IT ENTl        3801
138_L2 IT ENTl          37
Name: cell_type_alias_label, dtype: int64
142_L3 IT ENTm     670
235_L3 RSP-ACA     296
146_L3 IT ENTl    2052
140_L3 IT ENTm    1916
236_L3 RSP-ACA    3419
144_L3 IT ENTl     902
234_L3 RSP-ACA     499
141_L3 IT ENTm    2853
143_L3 IT ENTm    5259
145_L3 IT ENTl     137
Name: cell_type_alias_label, dtype: int64
Series([], Name: cell_type_alias_label, dtype: int64)
212_L5 IT TPE-ENT     2511
306_L5 NP CTX         6151
253_L5 PT CTX         3537
251_L5 PT CTX           95
239_L5 PT CTX          424
307_L5 NP C

In [11]:
cell_type_name = " ".join(matching_cell_types[0].split()[1:])

In [12]:
layer_distributions[0]

131_L2 IT RSPv       0.383501
186_L2 IT RSP-ACA    0.218963
130_L2 IT RSPv       0.015134
155_L2 IT ProS       0.051450
148_L2 IT PAR        0.036348
156_L2 IT ProS       0.002490
147_L2 IT PAR        0.014649
150_L2 IT ENTm       0.005465
151_L2 IT ENTm       0.008182
185_L2 IT RSP-ACA    0.005109
137_L2 IT ENTl       0.007438
153_L2 IT ENTm       0.054426
149_L2 IT PAR        0.006532
157_L2 IT HATA       0.043075
152_L2 IT ENTm       0.013323
154_L2 IT ProS       0.009799
139_L2 IT ENTl       0.122918
138_L2 IT ENTl       0.001197
Name: cell_type_alias_label, dtype: float64

In [13]:
def filter_lowly_expressed_genes(median_gene_expressions, num_genes=2500):
    proportion_nonzero_median = (median_gene_expressions != 0).sum(axis=1) / len(median_gene_expressions.values[0])
    mask = proportion_nonzero_median.nlargest(num_genes)
    filtered_median_gene_expressions = median_gene_expressions.loc[mask.index]
    
    return filtered_median_gene_expressions

In [14]:
class SyntheticAMBACortexDataset(SyntheticEmpiricalDataset):
    """Synthetic mouse brain cortex dataset with ciruclar pattterns.
    
    This class provides methods for initializing a semi-random mouse cortex spatial
    transcriptomics dataset, as well as methods to visualize aspects of the dataset.
    
    Data consists of 4 layers of widths [.35, .15, .25, .25]. Each layer has a
    unique excitatory neuronal type. There are three inhibitory neuronal
    types which have slight layer preferences. There are two layer-specific
    non-neuron types, one of which constitutes most of layer 2. There is a
    third non-neuron type, which is uniformly distributed throughout.
    0 - Excitatory L1
    1 - Excitatory L2
    2 - Excitatory L3
    3 - Excitatory L4
    4 - Inhibitory 1
    5 - Inhibitory 2
    6 - non-Neuron L1
    7 - non-Neuron (ubiquitous)

    Metagenes
    0 - Excitatory
    1 - In
    2 - Inhibitory-1
    3 - Inhibitory-2
    4 - non-Neuron 1
    5 - non-Neuron 2
    6 - L1
    7 - L2
    8 - L3
    9 - L4
    10 - end - random
    """
    
    distributions = layer_distributions
    
    layer_widths = [0.3, 0.1, 0.2, 0.2, 0.2]
    layer_endpoints = np.cumsum(layer_widths)
    
    mask_conditions = [
        (lambda coordinates: np.linalg.norm(coordinates, axis=1) < SyntheticAMBACortexDataset.layer_endpoints[0]),
        *[(lambda coordinates: (np.linalg.norm(coordinates, axis=1) >= SyntheticAMBACortexDataset.layer_endpoints[index])
             & (np.linalg.norm(coordinates, axis=1) < SynthetiAMBACortexrDataset.layer_endpoints[index + 1]))
            for layer in range(0, 3)
         ],
        (lambda coordinates: np.linalg.norm(coordinates, axis=1) >= SyntheticAMBACortexDataset.layer_endpoints[2])
    ]
    
    
    def __init__(self, parameters, parent_directory, key=''):
        num_genes = parameters["num_genes"]
        filtered_medians = filter_lowly_expressed_genes(medians, num_genes=num_genes)
        cell_type_definitions = [filtered_medians[layer_distribution.index.values] for layer_distribution in layer_distributions]
        super().__init__(SyntheticAMBACortexDataset.distributions,
                         cell_type_definitions,
                         SyntheticAMBACortexDataset.mask_conditions,
                         parameters, parent_directory, key='')
        

In [15]:
# Create Datasets
instances = 2
parent_directory = "../../data/synthetic_amba_cortex"
parameters_options = [{'num_cells': 2000, 'num_genes': 2500, 'num_replicates': 8,
             'sigX_scale': 3.0, 'sigY_scale': 2.0, 'lambda_s': 1.0,
             'gene_replace_prob': 0.0, 'element_replace_prob': 0.0}]

datasets = []
for parameters in parameters_options:
    for instance in range(instances):
        dataset = SyntheticAMBACortexDataset(parameters, parent_directory)
        datasets.append(dataset)
        dataset.save_pickle()
        dataset.reformat()

Synthesizing Y and p...


KeyError: 0

In [44]:
partition_indices = (np.cumsum(layer_distributions[0]) * 100).astype(int)  
np.split(np.arange(100), partition_indices)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37]),
 array([38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59]),
 array([60]),
 array([61, 62, 63, 64, 65]),
 array([66, 67, 68, 69]),
 array([], dtype=int64),
 array([70, 71]),
 array([], dtype=int64),
 array([72]),
 array([73]),
 array([], dtype=int64),
 array([74, 75, 76, 77, 78, 79]),
 array([], dtype=int64),
 array([80, 81, 82, 83, 84]),
 array([85]),
 array([86]),
 array([87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]),
 array([], dtype=int64),
 array([99])]